import { enrichTemplate } from './template-guidance.mjs';

// Authored resource definitions. Examples are teaching extensions, not client records.
const field = (label, help, example) => ({ label, help, example });
const column = (label, help, type = 'text') => ({ label, help, type });
const specSource = {
  title: 'Houzz Pro: specification-sheet structure',
  url: 'https://pro.houzz.com/pro-learn/blog/startup-guide-interior-design-how-to-make-spec-sheet-with-template',
};
const surveySource = {
  title: 'Leica Geosystems: room measurements and diagonal verification',
  url: 'https://shop.leica-geosystems.com/measurement-tools/disto/blog/video/speed-precision-smart-room-diagonals',
};

export function templateDefinitions(project) {
  const m = (id) => project.materials.find((item) => item.id === id);
  return [
    {
      id: 'client-questionnaire',
      slug: 'interior-design-client-questionnaire',
      title: 'Interior design client questionnaire',
      cluster: 'discover',
      wave: 1,
      format: 'docx',
      description:
        'Download an editable interior design client questionnaire with a worked example, discovery questions, and guidance for turning answers into a brief.',
      intro:
        'Begin with how the household lives, not with a shopping list. This client questionnaire separates everyday needs, preferences, practical constraints, and unanswered questions so the first meeting has a clear purpose.',
      use: 'Send the blank questionnaire before discovery, then review it together. Invite short answers and allow “not sure yet”; a missing answer is a follow-up task, not permission to assume. Store completed forms in your own secure project system, not on this website.',
      fields: [
        field(
          'Project and contact',
          'Record the project reference, preferred contact channel, and property location in your private copy. Ask only for contact information you need.',
          `${project.name}; illustrative example; no real client contact details.`,
        ),
        field(
          'Who uses the room?',
          'Ask about routines, visitors, pets, changing household needs, and any access requirements the client wants to share.',
          'Reading and conversation are the sample brief’s priorities. Household composition and access needs are not specified; confirm in discovery.',
        ),
        field(
          'What works today?',
          'Identify existing qualities worth keeping before discussing replacements.',
          project.constraints.join('; '),
        ),
        field(
          'What is difficult today?',
          'Ask for specific moments: where belongings collect, when light is uncomfortable, or how activities compete.',
          'The brief asks for reading, gathering, and storage to work together. Specific day-to-day frustrations still need a client conversation.',
        ),
        field(
          'What should it feel like?',
          'Request a few references and ask what the client likes about each: light, material, layout, or atmosphere. Do not assume they want every object shown.',
          'Quiet Oak is the selected illustrative route: pale oak, warm mineral walls, and linen. Deep Olive remains a comparison study.',
        ),
        field(
          'What must stay?',
          'List retained objects and fixed conditions. Confirm dimensions and condition separately at survey.',
          'Keep the existing oak floor, window position, and entrance position.',
        ),
        field(
          'Budget and timing',
          'Distinguish an overall allowance from design fees, purchasing, and installation. Record target dates and their reasons without promising feasibility.',
          'Budget and installation dates are not established in the sample; record as open decisions.',
        ),
        field(
          'Who decides, and what happens next?',
          'Identify who consolidates feedback and how decisions will be recorded. Agree the next meeting and outstanding information.',
          'Decision-maker not specified. Next step: confirm the brief and survey the room before developing selections.',
        ),
      ],
      steps: [
        'Send the questions with a short explanation of how answers will be used.',
        'Discuss conflicting priorities in discovery; record questions rather than resolving them silently.',
        'Transfer agreed needs into the brief and assign follow-up information to an owner.',
      ],
      mistakes: [
        'Do not treat an inspiration image as a specification.',
        'Do not convert an aspirational budget or date into a commitment.',
        'Do not collect unnecessary sensitive household information.',
      ],
      related: ['design-brief', 'site-survey', 'design-process'],
      sample: 'brief',
    },
    {
      id: 'design-brief',
      slug: 'interior-design-brief',
      title: 'Interior design brief template',
      cluster: 'discover',
      wave: 2,
      format: 'docx',
      description:
        'An editable residential interior design brief with objectives, constraints, priorities, decisions, and a clearly labeled Window Room example.',
      intro:
        'A useful brief turns discovery into a small set of decisions that the project can return to. It says what the room needs to do, what cannot change, and which questions still need an answer.',
      use: 'Complete this after discovery, not instead of discovery. Read the objectives back to the client in plain language. Revisit the brief when scope changes rather than quietly changing its meaning in a presentation.',
      fields: [
        field(
          'Project purpose',
          'Describe the change the project should achieve in one sentence, without naming products too early.',
          project.description,
        ),
        field(
          'Room and source information',
          'Record the room reference, dimension source, survey date, and confidence. Nominal dimensions are not site verification.',
          `${project.name}: ${project.dimensions.lengthMm} × ${project.dimensions.widthMm} mm; ceiling ${project.dimensions.heightMm} mm. Nominal sample dimensions, not a survey.`,
        ),
        field(
          'Functional priorities',
          'Rank activities and distinguish essential needs from optional additions.',
          'Bring reading, conversation, and storage into one room.',
        ),
        field(
          'Retained conditions',
          'State fixed conditions and what requires condition checks.',
          project.constraints.join('; '),
        ),
        field(
          'Design direction',
          'Name the agreed concept and explain why it serves the brief. Keep alternatives identifiable.',
          project.concepts[0].description,
        ),
        field(
          'Deliverables and exclusions',
          'List the proposed outputs; refer to a separate scope document for responsibility and limits.',
          'Illustrative brief, concept comparison, WR-01 furnished plan, WR-02 joinery elevation, and partial materials schedule. No construction-ready package.',
        ),
        field(
          'Open decisions',
          'Record the question, required information, owner, and next review. Unknown is a valid status.',
          'Wall finish area to survey; final sofa model and supplier to specify; budget and dates not established.',
        ),
        field(
          'Review record',
          'Capture the revision, reviewer, date, and what was agreed. A filled example is not actual approval.',
          'R0; pending review; no client approval represented.',
        ),
      ],
      steps: [
        'Extract needs and constraints from the questionnaire.',
        'Check each proposed deliverable against the objectives.',
        'Confirm unresolved items and review the brief before starting the next phase.',
      ],
      mistakes: [
        'Avoid vague aims such as “make it better” without explaining use.',
        'Do not hide exclusions in notes that nobody reviews.',
        'Do not treat a signed-off aesthetic direction as approval of dimensions or cost.',
      ],
      related: ['client-questionnaire', 'scope-of-work', 'concept-board'],
      sample: 'brief',
    },
    {
      id: 'proposal',
      slug: 'interior-design-proposal',
      title: 'Interior design proposal template',
      cluster: 'discover',
      wave: 1,
      format: 'docx',
      description:
        'Create a clear interior design proposal with an editable DOCX outline, sample project narrative, deliverables, assumptions, and next steps.',
      intro:
        'A proposal explains your understanding of the project and the work you propose to do. Use this editable structure to make the conversation concrete before a project agreement is prepared.',
      use: 'Adapt the outline to the services you actually offer. The example is a fictional teaching document with no quoted fee, real client, or enforceable terms. It is not a contract and does not replace professional legal review of an agreement.',
      fields: [
        field(
          'Project understanding',
          'Restate the client’s intended outcome and identify the information you have relied on.',
          `${project.name}: a 20 m² living-room study combining reading, conversation, and storage while retaining the existing floor and openings.`,
        ),
        field(
          'Proposed approach',
          'Explain the sequence and where client decisions will be needed.',
          'Confirm the brief, compare material directions, develop the selected concept, and assemble illustrative drawings and material references.',
        ),
        field(
          'Proposed deliverables',
          'Name each output and the level of development. Avoid an undefined promise of “all drawings”.',
          'One brief; Quiet Oak and Deep Olive comparison; selected Quiet Oak WR-01 and WR-02 samples; partial material schedule.',
        ),
        field(
          'Phases and reviews',
          'Describe review gates rather than inventing a universal project duration.',
          'Brief review → concept selection → drawing and material coordination → sample handoff. Dates to agree.',
        ),
        field(
          'Fee discussion',
          'List the services to be priced and the basis for discussion. Keep purchasing allowances separate from professional fees.',
          'No fee quoted. Design services, supplier purchasing, delivery, and installation allowances require separate discussion.',
        ),
        field(
          'Assumptions and exclusions',
          'Identify missing inputs, specialist work, procurement responsibilities, and what this proposal does not include.',
          'Nominal room data only. Site survey, engineering, permits, construction documentation, procurement commitments, and installation are not supplied by this example.',
        ),
        field(
          'Next steps',
          'Name the information needed to develop an agreement. Do not use this outline as a substitute for legal terms.',
          'Confirm scope and project information, discuss fees and responsibilities, then obtain an appropriate project agreement.',
        ),
      ],
      steps: [
        'Summarize discovery in the client’s language.',
        'Pair each proposed deliverable with a clear phase and review.',
        'Discuss assumptions and exclusions before preparing a separate agreement.',
      ],
      mistakes: [
        'Do not copy sample services into an offer you cannot deliver.',
        'Do not mix design fees with the furniture purchasing budget.',
        'Do not present this educational proposal outline as a legal contract.',
      ],
      related: ['scope-of-work', 'budget', 'timeline'],
      sample: 'brief',
    },
    {
      id: 'scope-of-work',
      slug: 'interior-design-scope-of-work',
      title: 'Interior design scope of work template',
      cluster: 'discover',
      wave: 2,
      format: 'docx',
      description:
        'Define interior design deliverables, responsibilities, exclusions, and review checkpoints with an editable scope-of-work planning template.',
      intro:
        '“Design the living room” can mean very different things to a client, a designer, and a contractor. A scope matrix makes the promised output and its boundary visible before work begins.',
      use: 'Use this as a planning attachment to a project discussion. Agree responsible parties and interfaces explicitly; this document contains no legal terms and does not replace a project agreement.',
      fields: [
        field(
          'Project boundary',
          'Name included rooms and distinguish work areas from adjacent coordination areas.',
          'The Window Room only. No adjacent-room redesign represented.',
        ),
        field(
          'Discovery and brief',
          'List the information to gather and the output to review.',
          'Review provided room data and prepare an illustrative brief. Site verification remains outstanding.',
        ),
        field(
          'Concept development',
          'State what will be compared and what happens after selection.',
          'Compare Quiet Oak and Deep Olive; continue only Quiet Oak into the sample drawings and materials.',
        ),
        field(
          'Drawings and schedules',
          'Specify document names, intended use, and level of detail.',
          'WR-01 furnished plan; WR-02 joinery elevation; partial material schedule. R0 illustrative documents, pending review.',
        ),
        field(
          'Responsibilities',
          'Record who provides measurements, approves selections, coordinates specialists, and places orders. Leave unresolved roles explicit.',
          'Surveyor, reviewer, purchasing party, and installation party not appointed in this example.',
        ),
        field(
          'Review checkpoints',
          'Define when feedback is required and who consolidates it. Put revision allowances in the separately agreed scope.',
          'Brief, concept, and coordination reviews proposed; review dates and revision allowances not agreed.',
        ),
        field(
          'Exclusions and interfaces',
          'List omitted services and information you must receive from others.',
          'No structural design, electrical design, code assessment, permit application, order placement, or construction supervision in the sample.',
        ),
        field(
          'Change record',
          'Document a requested change and its potential effect before altering the baseline.',
          'No approved scope changes. Record new requests with an owner and impact review.',
        ),
      ],
      steps: [
        'Name the deliverable and its intended use.',
        'Assign responsibility at each handoff, including work provided by others.',
        'Record changes against the agreed baseline rather than overwriting it.',
      ],
      mistakes: [
        'An exclusion is not a complete plan unless someone owns the interface.',
        'A concept drawing is not automatically a construction document.',
        'A task list without an agreed boundary does not define scope.',
      ],
      related: ['proposal', 'design-brief', 'project-management'],
      sample: 'handoff',
    },
    {
      id: 'budget',
      slug: 'interior-design-budget',
      title: 'Interior design budget template',
      cluster: 'coordinate',
      wave: 1,
      format: 'xlsx',
      budget: true,
      description:
        'Download an editable interior design budget spreadsheet with working totals, variance formulas, a blank sheet, and an illustrative worked example.',
      intro:
        'Separate quantity, unit cost, and additional allowances before comparing an item with its budget. This workbook keeps those inputs visible instead of burying delivery and installation inside a single unexplained total.',
      use: 'Choose one currency for the workbook and replace all illustrative figures with project-specific inputs. Enter additional costs as amounts, not assumed tax percentages. Blank quantities or prices leave the calculated total blank; zero is a deliberate numeric input.',
      columns: [
        column('Reference', 'Use the same item ID as the schedule.'),
        column('Item', 'Describe the selection without treating it as an order.'),
        column('Quantity', 'Use the quantity appropriate to the unit.', 'number'),
        column('Unit', 'Keep items, modules, and area units distinct.'),
        column('Unit cost', 'Enter a verified price or clearly identified allowance.', 'money'),
        column(
          'Additional allowance',
          'Record combined additional amounts; explain what is included in the notes.',
          'money',
        ),
        column(
          'Estimated total',
          'Quantity × unit cost + additional allowance. Calculated only when quantity and unit cost exist.',
          'formula',
        ),
        column('Budget allowance', 'Enter the comparison budget in the same currency.', 'money'),
        column(
          'Remaining / (over)',
          'Budget allowance minus estimated total. Negative means over the entered allowance.',
          'formula',
        ),
        column('Notes', 'Record quote source, currency, exclusions, and date.'),
      ],
      rows: [
        [
          m('F-01').id,
          m('F-01').name,
          1,
          'item',
          1200,
          100,
          null,
          1500,
          null,
          'USD teaching figures only; no supplier quote or tax assumption.',
        ],
        [
          m('F-02').id,
          m('F-02').name,
          1,
          'item',
          500,
          50,
          null,
          500,
          null,
          'USD teaching figures only; excludes installation.',
        ],
        [
          m('FIN-02').id,
          m('FIN-02').name,
          null,
          'm²',
          null,
          null,
          null,
          null,
          null,
          'Area and rate unknown; do not read blank as free.',
        ],
      ],
      steps: [
        'Set a currency and list the items in scope.',
        'Replace example rates with dated quotes or explicitly labeled allowances.',
        'Review negative variance and unresolved inputs before discussing a project total.',
      ],
      mistakes: [
        'Do not add mixed currencies or unlike area units.',
        'A blank line is unresolved, not a zero-cost item.',
        'Do not treat the example total as a complete renovation budget.',
      ],
      related: ['ffe-schedule', 'procurement', 'proposal'],
      sample: 'materials',
    },
    {
      id: 'spec-sheet',
      slug: 'interior-design-spec-sheet',
      title: 'Interior design spec sheet template',
      cluster: 'coordinate',
      wave: 1,
      format: 'xlsx',
      description:
        'Download an editable interior design specification sheet with product references, dimensions, supplier fields, approval status, and a worked example.',
      intro:
        'A specification sheet records what an item is meant to be. It should let someone distinguish the proposed product, finish, size, and revision without inferring those details from an image.',
      use: 'Use the sheet for product-level information. Keep the FF&E schedule as the room-by-room quantity register and the finish schedule as the surface register. Terminology varies between practices; agree the role of each document with the people using it.',
      columns: [
        column('Reference', 'Stable ID carried into plans and schedules.'),
        column('Selection', 'A proposed product or clearly labeled concept.'),
        column('Application', 'Where the item is used.'),
        column(
          'Dimensions / unit',
          'State all relevant dimensions and units; leave unknowns explicit.',
        ),
        column('Material / finish', 'Name the finish and sample reference if verified.'),
        column('Supplier / model', 'Record a verified supplier and model before order approval.'),
        column(
          'Source / quote date',
          'Identify the source and date for supplied product information.',
        ),
        column('Status', 'Distinguish proposed, pending review, and approved.'),
        column('Revision', 'Identify the current issue.'),
        column('Review note', 'Record unresolved dimensions, suitability, and coordination.'),
      ],
      rows: [
        [
          'F-01',
          m('F-01').name,
          m('F-01').application,
          'Not specified',
          'Linen; final fabric to confirm',
          'Not specified',
          'No supplier quote',
          'Pending review',
          'R0',
          m('F-01').note,
        ],
        [
          'J-01',
          m('J-01').name,
          m('J-01').application,
          '3 × 800 mm nominal modules',
          'Pale oak',
          'Custom concept; maker not appointed',
          'WR-02 sample drawing',
          'Pending review',
          'R0',
          'Fixings, tolerances, substrate, and final fabrication details unresolved.',
        ],
      ],
      steps: [
        'Assign a reference before adding the item to a drawing.',
        'Record sourced information separately from assumptions.',
        'Review the specification alongside its room schedule and drawings before any purchasing decision.',
      ],
      mistakes: [
        'An image is not proof of model, dimensions, or finish.',
        'Do not overwrite a revision without recording the change.',
        'Do not label an item approved because it appears in a concept board.',
      ],
      sources: [specSource],
      related: ['ffe-schedule', 'finish-schedule', 'elevation-guide'],
      sample: 'materials',
    },
    {
      id: 'ffe-schedule',
      slug: 'ffe-schedule',
      title: 'FF&E schedule template',
      cluster: 'coordinate',
      wave: 1,
      format: 'xlsx',
      description:
        'An editable furniture, fixtures, and equipment schedule with room references, quantities, specification links, and delivery-review fields.',
      intro:
        'The FF&E schedule is the room-by-room register of selected items. Its job is coordination: what belongs where, how many are proposed, and which information is still needed before an order can be considered.',
      use: 'Agree the classification boundary with your team. In this library, furniture and the loose rug sit in this register; the retained floor belongs in the finish schedule and built-in joinery stays linked to its drawing and specification. This is a documentation convention, not a universal accounting rule.',
      columns: [
        column('Room', 'Use a stable room name or number.'),
        column('Reference', 'Match the plan and product specification.'),
        column('Item', 'Describe the proposed selection.'),
        column('Quantity', 'Count items; do not confuse a set with individual units.', 'number'),
        column('Unit', 'Use an explicit purchasing unit.'),
        column('Specification reference', 'Point to the current product specification.'),
        column('Approval', 'Track selection approval separately from an order.'),
        column('Order / delivery', 'Record actual order status only when confirmed.'),
        column('Review note', 'Identify missing model, access, or suitability information.'),
      ],
      rows: ['F-01', 'F-02', 'T-01'].map((id) => [
        project.name,
        id,
        m(id).name,
        m(id).quantity,
        m(id).unit,
        `${id}; product details to develop`,
        'Pending review',
        'Not ordered',
        m(id).note,
      ]),
      steps: [
        'List items by room and stable reference.',
        'Reconcile quantities with the furnished plan.',
        'Confirm specification, approval, purchasing responsibility, and delivery constraints before ordering.',
      ],
      mistakes: [
        'Do not count one item again merely because it appears on two drawings.',
        'Selection approval and order confirmation are different states.',
        'Do not use a partial sample register as a complete purchasing list.',
      ],
      related: ['spec-sheet', 'ffe-guide', 'procurement'],
      sample: 'materials',
    },
    {
      id: 'finish-schedule',
      slug: 'finish-schedule',
      title: 'Finish schedule template',
      cluster: 'coordinate',
      wave: 1,
      format: 'xlsx',
      description:
        'Download a room finish schedule spreadsheet connecting floors, walls, and other surfaces to finish references, quantities, and review notes.',
      intro:
        'A finish schedule answers a spatial question: which treatment applies to which surface? It connects room and surface references to a defined finish, without pretending that every material quantity is already known.',
      use: 'Record each surface separately when treatments or preparation differ. The Window Room’s 20 m² is a nominal floor footprint, not a wall area, coverage calculation, or purchasing quantity. Verify substrate condition and product requirements independently.',
      columns: [
        column('Room', 'Name the room consistently.'),
        column('Surface', 'Specify floor, wall face, ceiling, or another identifiable surface.'),
        column('Finish reference', 'Match the material register and relevant drawing.'),
        column('Finish', 'Name retained conditions as well as new treatments.'),
        column('Quantity', 'Leave an unmeasured surface blank.', 'number'),
        column('Unit', 'State the measured or counted unit.'),
        column('Preparation / condition', 'Record what needs survey or specialist assessment.'),
        column('Status', 'Record the review state.'),
        column('Drawing / note', 'Link the application to a current document.'),
      ],
      rows: [
        [
          project.name,
          'Floor',
          'FIN-01',
          m('FIN-01').name,
          m('FIN-01').quantity,
          m('FIN-01').unit,
          'Retain; verify condition on site',
          'Pending review',
          'WR-01; footprint only, not an order quantity',
        ],
        [
          project.name,
          'Walls',
          'FIN-02',
          m('FIN-02').name,
          null,
          'm²',
          'Area, substrate, and preparation to survey',
          'Pending review',
          'No verified wall-area takeoff',
        ],
      ],
      steps: [
        'List room surfaces and exceptions.',
        'Assign finish references and link to approved product information when available.',
        'Review quantities, substrate conditions, and drawing consistency before preparing procurement information.',
      ],
      mistakes: [
        'Do not substitute floor area for wall area.',
        'Do not assume one wall treatment applies to every wall face.',
        'Do not invent waste factors or coverage rates without product and project information.',
      ],
      related: ['spec-sheet', 'material-board', 'room-data'],
      sample: 'materials',
    },
    {
      id: 'room-data',
      slug: 'room-data-sheet',
      title: 'Room data sheet template',
      cluster: 'discover',
      wave: 2,
      format: 'xlsx',
      description:
        'Keep room dimensions, functional requirements, finishes, source references, and unresolved information together in an editable room data sheet.',
      intro:
        'A room data sheet is a concise requirements register. It brings together what is known about one room while keeping the source and status of each entry visible.',
      use: 'Use one room identifier throughout the project. A requirements entry describes intent; a measured entry needs a survey source. Do not convert either into a verified technical specification merely by placing it in a spreadsheet.',
      columns: [
        column('Room', 'Stable room name or number.'),
        column('Topic', 'Group geometry, use, constraints, or finishes.'),
        column('Requirement / value', 'Record one clear statement per row.'),
        column('Unit', 'Include units for numeric dimensions.'),
        column('Source', 'Identify the brief, survey, or drawing.'),
        column('Status', 'Distinguish nominal, proposed, and verified.'),
        column(
          'Action / owner',
          'Name the next information request and responsible person when appointed.',
        ),
      ],
      rows: [
        [
          project.name,
          'Length',
          project.dimensions.lengthMm,
          'mm',
          'Illustrative project fixture',
          'Nominal; not surveyed',
          'Verify on site; owner to appoint',
        ],
        [
          project.name,
          'Width',
          project.dimensions.widthMm,
          'mm',
          'Illustrative project fixture',
          'Nominal; not surveyed',
          'Verify on site; owner to appoint',
        ],
        [
          project.name,
          'Ceiling height',
          project.dimensions.heightMm,
          'mm',
          'Illustrative project fixture',
          'Nominal; not surveyed',
          'Check variations; owner to appoint',
        ],
        [
          project.name,
          'Use',
          'Reading, conversation, storage',
          '',
          'Sample brief',
          'Illustrative intent',
          'Review priorities',
        ],
        [
          project.name,
          'Floor',
          'Retain existing oak; FIN-01',
          '',
          'Sample brief / WR-01',
          'Pending review',
          'Survey condition',
        ],
      ],
      steps: [
        'Assign the room reference before capturing requirements.',
        'Record the source and status alongside every important fact.',
        'Review open actions when the brief or survey changes.',
      ],
      mistakes: [
        'A precise-looking number can still be nominal.',
        'Do not mix requirements with verified performance results.',
        'Do not duplicate a fact in several registers without a clear source of truth.',
      ],
      related: ['site-survey', 'design-brief', 'finish-schedule'],
      sample: 'brief',
    },
    {
      id: 'timeline',
      slug: 'interior-design-project-timeline',
      title: 'Interior design project timeline template',
      cluster: 'handoff',
      wave: 3,
      format: 'xlsx',
      description:
        'An editable interior design phase planner with owners, dates, dependencies, review milestones, and a worked example without invented deadlines.',
      intro:
        'A useful timeline explains what must happen before the next activity can start. It is more than a colored sequence of dates: every review gate needs an output, an owner, and enough information for a decision.',
      use: 'The worked example shows sequence, not a promised duration. Enter dates only after confirming scope, decision availability, and supplier information. Keep dependencies understandable rather than hiding them in an unsupported automatic scheduler.',
      columns: [
        column('Phase', 'Name a phase or work package.'),
        column('Output', 'State what must exist at the end.'),
        column('Owner', 'Assign a real person or role when agreed.'),
        column(
          'Planned start',
          'Enter a project-specific date; example intentionally blank.',
          'date',
        ),
        column(
          'Planned finish',
          'Allow time for review rather than assuming instant approval.',
          'date',
        ),
        column('Depends on', 'Name the prerequisite output or decision.'),
        column('Review milestone', 'Describe the decision that allows progress.'),
        column('Status', 'Record an actual state, not a guessed completion percentage.'),
      ],
      rows: [
        [
          'Discovery',
          'Agreed brief and information requests',
          'To appoint',
          null,
          null,
          'Project information',
          'Confirm objectives and constraints',
          'Planning example',
        ],
        [
          'Concept',
          'Selected material direction',
          'To appoint',
          null,
          null,
          'Brief review',
          'Select Quiet Oak or revise direction',
          'Planning example',
        ],
        [
          'Coordination',
          'WR-01, WR-02, partial material schedule',
          'To appoint',
          null,
          null,
          'Concept selection and verified inputs',
          'Review references and open issues',
          'Planning example',
        ],
        [
          'Handoff',
          'Indexed issue package',
          'To appoint',
          null,
          null,
          'Coordination review',
          'Confirm recipients and outstanding actions',
          'Planning example',
        ],
      ],
      steps: [
        'List phase outputs before adding dates.',
        'Name dependencies and the people responsible for reviews.',
        'Revise future dates when a prerequisite changes and record the reason.',
      ],
      mistakes: [
        'Do not copy durations from another project without checking scope.',
        'A planned review date is not approval.',
        'Do not let an outdated supplier lead time become an invisible schedule assumption.',
      ],
      related: ['project-management', 'design-process', 'proposal'],
      sample: 'handoff',
    },
    {
      id: 'site-survey',
      slug: 'interior-design-site-survey-checklist',
      title: 'Interior design site survey checklist',
      cluster: 'discover',
      wave: 2,
      format: 'docx',
      description:
        'An editable interior design site-survey checklist for dimensions, openings, visible conditions, photo references, and follow-up information.',
      intro:
        'Survey notes are useful only if another person can understand what was measured, where it was measured, and what remains unknown. This checklist provides a consistent structure for that record.',
      use: 'Prepare the sheet before a visit and follow site access and safety arrangements. Record visible conditions without opening concealed assemblies or diagnosing services. Use suitable professionals for specialist surveys and any safety or compliance assessment.',
      fields: [
        field(
          'Visit and room reference',
          'Record date, surveyor, access limitations, instruments, and room identifier.',
          'The Window Room; no site visit has occurred. This is a teaching example.',
        ),
        field(
          'Room geometry',
          'Record each wall run, overall checks, diagonals where practical, and measurement units. Mark missing measurements.',
          'Nominal source: 5000 × 4000 mm; ceiling 2800 mm. Diagonals, wall irregularities, and actual dimensions remain unverified.',
        ),
        field(
          'Openings',
          'Locate each opening relative to an identified corner and record relevant sizes, heights, and swing or operation.',
          'Window and entrance positions are retained in the sample. Exact opening sizes and offsets require survey.',
        ),
        field(
          'Existing finishes and retained objects',
          'Photograph condition and record dimensions of objects that must remain.',
          'FIN-01 existing oak floor to retain. Condition has not been assessed.',
        ),
        field(
          'Visible services and obstructions',
          'Locate visible devices and access panels without claiming concealed routes or suitability.',
          'Service positions not surveyed. Obtain specialist information before coordination.',
        ),
        field(
          'Photograph register',
          'Give each image a reference, room, direction, and note. Obtain permission before photographing occupied spaces.',
          'No site photographs. Published room imagery is AI-generated concept illustration, not survey evidence.',
        ),
        field(
          'Checks and discrepancies',
          'Record differences between provided plans and observations without silently averaging conflicting measurements.',
          'No measurement comparison completed. Do not use the sample drawing as site evidence.',
        ),
        field(
          'Follow-up actions',
          'Record missing information, its owner, and when it must be resolved.',
          'Arrange a measured survey and confirm access limitations before using dimensions for project work.',
        ),
      ],
      steps: [
        'Prepare a room reference and rough sketch before the visit.',
        'Record dimensions and photo references as you work, including inaccessible areas.',
        'Check completeness and list discrepancies before leaving; arrange any necessary specialist follow-up.',
      ],
      mistakes: [
        'Do not treat a photo as a scaled measurement.',
        'Do not assume concealed services from visible fittings.',
        'Do not omit access limitations from the resulting record.',
      ],
      sources: [surveySource],
      related: ['measure-room', 'room-data', 'drawing-checklist'],
      sample: 'brief',
    },
    {
      id: 'presentation',
      slug: 'interior-design-presentation',
      title: 'Interior design presentation templates (PPTX and DOCX)',
      cluster: 'design',
      wave: 3,
      format: 'docx',
      description:
        'Download editable PowerPoint slides, a DOCX storyboard, and a PDF preview with composed mood boards, design rationale, and an illustrative room example.',
      intro:
        'A client presentation should make a decision easier. Use the editable PowerPoint deck to present the brief, mood boards, references and review decisions; use the DOCX storyboard to plan the narrative.',
      use: 'Download the blank PPTX and replace its editable text, palette swatches, diagram shapes and image placeholders. The worked PPTX and PDF preview show the illustrative Window Room. The companion DOCX is a planning storyboard. You can also import the PPTX into Google Slides; check fonts, image crops and line breaks again after adding your own material.',
      fields: [
        field(
          'Opening: purpose of the review',
          'Explain what the client is being asked to decide today and what is not yet ready for approval.',
          'Review the illustrative material direction for The Window Room; no procurement or construction approval requested.',
        ),
        field(
          'Brief recap',
          'Show the essential needs and retained conditions before proposing a solution.',
          'Reading, conversation, and storage; retain existing oak floor and opening positions.',
        ),
        field(
          'Existing information',
          'Place a plan or survey image with its source and status clearly labeled.',
          '[Insert verified project information here.] The sample has nominal dimensions only; concept imagery is not a survey.',
        ),
        field(
          'Selected direction',
          'Place the concept image and explain how the proposal responds to the brief.',
          '[Insert Quiet Oak concept image.] Pale oak, mineral walls, and linen support the selected calm direction. AI-generated concept illustration.',
        ),
        field(
          'Alternative and tradeoff',
          'Compare a specific decision on equal terms; do not change multiple constraints invisibly.',
          '[Insert Deep Olive comparison image.] Darker joinery and olive upholstery are an alternative study, not the downstream selection.',
        ),
        field(
          'Layout and references',
          'Show a readable plan and identify the items discussed. Label the drawing’s status.',
          '[Insert WR-01 sample plan.] F-01 sofa, F-02 reading chair, and J-01 storage remain illustrative and pending review.',
        ),
        field(
          'Materials and open questions',
          'Separate the proposed visual palette from verified product selections.',
          'FIN-01 floor retained; FIN-02 wall area to survey; final F-01 model not specified.',
        ),
        field(
          'Decision and next steps',
          'List the requested decision, person responsible, and information needed for the next review.',
          'Record feedback on direction, confirm unresolved requirements, and develop verified project information before detailed coordination.',
        ),
      ],
      steps: [
        'Write the decision request before arranging images.',
        'Use consistent references and comparable views for alternatives.',
        'Record feedback against the relevant decision rather than relying on presentation notes alone.',
      ],
      mistakes: [
        'Do not request blanket approval of a mixed-status package.',
        'Do not hide unresolved cost or dimensional questions behind polished visuals.',
        'Do not label concept imagery as completed client work.',
      ],
      related: ['mood-board', 'concept-board', 'project-management'],
      sample: 'design',
    },
  ]
    .map(enrichTemplate)
    .map((item) => ({
      ...item,
      kind: 'template',
      path: `templates/${item.slug}/`,
      status: 'published',
      modified: item.modified,
      sources: item.sources || [],
    }));
}
